# Generated by Django 3.2.16 on 2024-01-21 17:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_myformdata_rich_text_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myformdata',
            name='rich_text_field',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
