# Generated by Django 3.2.16 on 2024-01-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_myformdata_rich_text_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myformdata',
            name='rich_text_field',
            field=models.TextField(default=''),
        ),
    ]
